FROM php:7.2-fpm
COPY php.ini /usr/local/etc/php/


# FROM  nginx:latest

# # author
# # MAINTAINER  kasai

# # ADD default.conf /etc/nginx/conf.d

# # RUN echo "now building..."

# COPY src /usr/share/nfinx/html